### ISSUE TITLE
[Bug]: cannot access net.minecraft.server.level.EntityPlayer

### ISSUE THREAD

**Issue by NotZer0Two** [HorseNuggets/TerminatorPlus#47]
### What happened?

Trying to build the plugin with Idea say this error

### Plugin Version

3.1-BETA

### Server Version

spigot-api-1.18.2-R0.1-20220312.205138-16-shaded

### Relevant log output

```shell
java: cannot access net.minecraft.server.level.EntityPlayer
  class file for net.minecraft.server.level.EntityPlayer not found
```

### Additional Context

Trying to build the error start from the Bot bot = Bot.createBot

### Checklist

- [X] My issue does not match any existing issues on this repo

**Comment by Badbird-5907** [comment]
This version only supports 1.18.1, did you run buildtools for 1.18.1?

**Comment by NotZer0Two** [comment]
> This version only supports 1.18.1, did you run buildtools for 1.18.1?

yes i runned the 1.18.2 api on the plugin
