### ISSUE TITLE
[Bug]: class file for net.minecraft.server.level.EntityPlayer not found

### ISSUE THREAD

**Issue by NotZer0Two** [HorseNuggets/TerminatorPlus#48]
### What happened?

Trying to build the plugin with Idea say this error

### Plugin Version

3.1-BETA

### Server Version

spigot-api-1.18.1-R0.1-20220219.222924-77-shaded

### Relevant log output

```shell
java: cannot access net.minecraft.server.level.EntityPlayer
  class file for net.minecraft.server.level.EntityPlayer not found
```

### Additional Context

part the code where is the error is from Bot bot = Bot.createBot(loc, name);

### Checklist

- [X] My issue does not match any existing issues on this repo

**Comment by NotZer0Two** [comment]
Already submited but seem the error is not fixed again after i trying to use what the collaborator said

**Comment by Badbird-5907** [comment]
Use 1.18.1

**Comment by Badbird-5907** [comment]
did you run 1.18.1 build tools & also are you using mojmaps?

**Comment by Badbird-5907** [comment]
pre-compiled binaries can be found in the discord @ https://discord.gg/25Y5QBudBK
