### ISSUE TITLE
Would you mind telling me how to install it?

### ISSUE THREAD

**Issue by KarieBob** [HorseNuggets/TerminatorPlus#6]
Would you mind telling me how to install it?

**Comment by SUDG01** [comment]
yes

**Comment by KarieBob** [comment]
> yes

how to use it

**Comment by Legit4K** [comment]
> Would you mind telling me how to install it?

The Jar is available on his discord server [here](https://discord.gg/horsenuggets)
Some examples of commands are: `/terminatorplus`, `/bot`, `/ai` they provide more info when used

**Comment by KarieBob** [comment]
Thank you for your timely help! I have already installed it into my spigot sever.
