### ISSUE TITLE
[Bug]:  /bot settings mobtarget is not working

### ISSUE THREAD

**Issue by Ianzhao071102** [HorseNuggets/TerminatorPlus#60]
### What happened?

/bot settings mobtarget <boolean>

The boolean value,
I tried : 
true, 1, yes, positive

But they don't work.

Also, AIs are mining bedrock and barrier blocks to get me.
Plz, fix this.

At last, they are bad at swimming, also digging into the lava but suddenly boat clutching.

### Plugin Version

3.1-BETA

### Server Version

Spigot 1.18.2

### Checklist

- [x] My issue does not match any existing issues on this repo

**Comment by Badbird5907** [comment]
You are using an old unsupported version that does not include those features
