### ISSUE TITLE
[Feature] 1.21/1.21.1 support

### ISSUE THREAD

**Issue by DxrkCat** [HorseNuggets/TerminatorPlus#67]
### Feature Request

bump

### Checklist

- [X] My suggestion does not match any existing suggestions on this repo

**Comment by Badbird5907** [comment]
I will add support when I have time (at least 1-2 weeks). Please note that development on this plugin has been paused indefinitely, and version updates are not guaranteed.
If you would like to try updating the plugin to 1.21 yourself, please have a look at [this commit in paperweight-test-plugin](https://github.com/PaperMC/paperweight-test-plugin/commit/3f2a19d0dc81d345c38d4119b94a60b0aa37b67b).

The corresponding gradle build file can be found [here](https://github.com/HorseNuggets/TerminatorPlus/blob/master/TerminatorPlus-Plugin/build.gradle.kts#L16)

**Comment by TheMisterFish** [comment]
Closed by https://github.com/HorseNuggets/TerminatorPlus/pull/70?

**Comment by Badbird5907** [comment]
Closed by #70
