### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by CivetSR** [HorseNuggets/TerminatorPlus#7]
**Describe the feature you'd like added**
A clear and concise description of what you want added or changed.

**Describe alternatives you've considered**

**Additional context**

**Comment by KarieBob** [comment]
I don't know

**Comment by BattleDash** [comment]
Please ask for help in the Discord Server, not in github issues.

**Comment by KarieBob** [comment]
> Please ask for help in the Discord Server, not in github issues.

Where is the 'Disord Sever'
