### ISSUE TITLE
[Bug]: bots cant jump over full blocks in new 1.21.1 version

### ISSUE THREAD

**Issue by Jayrock09** [HorseNuggets/TerminatorPlus#72]
### What happened?

they cant jump over full blocks (had to compress video)

https://github.com/user-attachments/assets/8467218d-cb6b-4a64-8549-130c4eefc65a

### Plugin Version

4.5.0-BETA

### Server Version

paper 1.21.1

### Checklist

- [X] My issue does not match any existing issues on this repo

**Comment by Badbird5907** [comment]
Interesting...
Afaik, the movement code hasn't been touched in a while. This may be an issue introduced in PR #68, will need to investigate.
Could you please also send the link `tplus debuginfo` returns?

Additionally:
If you have time, could you please [test this unreleased version](https://cdn.badbird.dev/screenshots/2024/12/TerminatorPlus-4.4.0-BETA.jar) on **1.20.4**?
Thanks.

**Comment by Jayrock09** [comment]
testing the unreleased version right now, i will have to recreate that scene i made though since i closed that server

**Comment by Jayrock09** [comment]
THIS IS THE UNRELEASED VERSION LOG NOT THE 1.21.1 LOG i will send that soon

**Comment by Jayrock09** [comment]
https://mclo.gs/tVaFzH6

**Comment by Jayrock09** [comment]
jumping seems fine btw on the unreleased version

**Comment by Badbird5907** [comment]
Interesting...
@TheMisterFish are you able to recreate this?

**Comment by Jayrock09** [comment]
https://mclo.gs/gRplHqa

**Comment by TheMisterFish** [comment]
Will have a look at it. My first assumption is this part: https://github.com/HorseNuggets/TerminatorPlus/blob/master/TerminatorPlus-Plugin%2Fsrc%2Fmain%2Fjava%2Fnet%2Fnuggetmc%2Ftplus%2Fbot%2FBot.java#L485-L488

**Comment by Badbird5907** [comment]
![image](https://github.com/user-attachments/assets/eed5d9f1-c940-4661-9c6a-be972ac42a59)

That line hasn't been changed in ~3 years though. You could try increasing it.

**Comment by TheMisterFish** [comment]
Instead of introducing a new variable, it would also be possible to check if `jumpTicks - 2 == 0`

**Comment by Badbird5907** [comment]
This should be fine, please create a PR!

**Comment by TheMisterFish** [comment]
> This should be fine, please create a PR!

https://github.com/HorseNuggets/TerminatorPlus/pull/73

**Comment by Badbird5907** [comment]
@Jayrock09 could you please verify if this is still happening on the latest version?

**Comment by Badbird5907** [comment]
Closed by #73
